#:import MarkdownLexer pygments.lexers.markup.MarkdownLexer

<BaseScreen>:
    name: 'base'

    BoxLayout:

        ScreenManager:
            id: manager

            Screen:
                name: 'fm_screen'
                FloatLayout:
                    id: fm

            Screen:
                name: 'note_editor_screen'
                CodeInput:
                    id: note_editor
                    lexer: MarkdownLexer()