<AboutScreen>:
    FloatLayout:

        BoxLayout:
            id: box
            orientation: 'vertical'
            padding: dp(0), dp(10)

            Widget:
            Widget:

            Label:
                id: label
                font_size: '14sp'
                bold: True
                color: app.theme_cls.text_color
                markup: True
                halign: 'center'
                on_ref_press: root.open_url(*args)

            Widget:
            Widget:
